#!/usr/bin/env bash
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export DB_USER="jabba"
export DB_PASSWORD="hutt"
export DB_HOST="127.0.0.1"
export DB_PORT="3306"
export DB_NAME="accounts"
export PANTS_DISTDIR=/home/oleg/projects/python/jabbas_pizza/dist
export JWT_SECRET="some-long-random-string"


GEN_PY_PATH="${ROOT_DIR}/protobuf/gen_py"
PYTHONPATH_COMPONENTS=("$ROOT_DIR" "$GEN_PY_PATH")
NEW_PYTHONPATH=""

for component in "${PYTHONPATH_COMPONENTS[@]}"; do
  case ":${NEW_PYTHONPATH:-}:" in
    *":${component}:"*) continue ;;
    *)
      if [[ -z "${NEW_PYTHONPATH}" ]]; then
        NEW_PYTHONPATH="${component}"
      else
        NEW_PYTHONPATH="${NEW_PYTHONPATH}:${component}"
      fi
      ;;
  esac
done

if [[ -n "${PYTHONPATH:-}" ]]; then
  NEW_PYTHONPATH="${NEW_PYTHONPATH}:${PYTHONPATH}"
fi
export PYTHONPATH="${NEW_PYTHONPATH}"

source "${ROOT_DIR}/.venv/bin/activate"
export PATH="$HOME/.local/bin:$PATH"
PS1="(jabba) ${PS1#\(*\) }"
